export const users = {
  data: [
    {
      id: "1",
      role: "front end",
      email: "ken99@yahoo.com",
      phone: "0944627892",
      fullname: "david ken",
      status: true,
    },
    {
      id: "2",
      role: "back end",
      status: true,
      email: "Abe45@gmail.com",
      fullname: "david Abe",
      phone: "0944627892",
    },
    {
      id: "3",
      role: "front end",
      status: false,
      email: "Monserrat44@gmail.com",
      fullname: "david Monserrat",
      phone: "0944627892",
    },
    {
      id: "4",
      role: "ux/ui",
      status: true,
      email: "Silas22@gmail.com",
      fullname: "david Silas",
      phone: "0944627892",
    },
    {
      id: "5",
      role: "ux/ui",
      status: true,
      email: "carmella@hotmail.com",
      fullname: "david carmella",
      phone: "0944627892",
    },
    {
      id: "6",
      role: "back end",
      status: false,
      email: "ken99@yahoo.com",
      fullname: "david ken",
      phone: "0944627892",
    },
    {
      id: "7",
      role: "back end",
      status: true,
      email: "Abe45@gmail.com",
      fullname: "david abe",
      phone: "0944627892",
    },
    {
      id: "8",
      role: "ux/ui",
      status: true,
      email: "Monserrat44@gmail.com",
      fullname: "david Monserrat",
      phone: "0944627892",
    },
    {
      id: "9",
      role: "front end",
      status: true,
      email: "Silas22@gmail.com",
      phone: "0944627892",
      fullname: "david Silas",
    },
    {
      id: "10",
      role: "front end",
      status: true,
      phone: "0944627892",
      email: "carmella@hotmail.com",
      fullname: "david carmella",
    },
    {
      id: "11",
      role: "front end",
      email: "ken99@yahoo.com",
      phone: "0944627892",
      fullname: "david ken",
      status: true,
    },
    {
      id: "12",
      role: "back end",
      status: true,
      email: "Abe45@gmail.com",
      fullname: "david Abe",
      phone: "0944627892",
    },
    {
      id: "13",
      role: "front end",
      status: false,
      email: "Monserrat44@gmail.com",
      fullname: "david Monserrat",
      phone: "0944627892",
    },
    {
      id: "14",
      role: "ux/ui",
      status: true,
      email: "Silas22@gmail.com",
      fullname: "david Silas",
      phone: "0944627892",
    },
    {
      id: "15",
      role: "ux/ui",
      status: true,
      email: "carmella@hotmail.com",
      fullname: "david carmella",
      phone: "0944627892",
    },
    {
      id: "16",
      role: "back end",
      status: false,
      email: "ken99@yahoo.com",
      fullname: "david ken",
      phone: "0944627892",
    },
    {
      id: "17",
      role: "back end",
      status: true,
      email: "Abe45@gmail.com",
      fullname: "david abe",
      phone: "0944627892",
    },
    {
      id: "18",
      role: "ux/ui",
      status: true,
      email: "Monserrat44@gmail.com",
      fullname: "david Monserrat",
      phone: "0944627892",
    },
    {
      id: "19",
      role: "front end",
      status: true,
      email: "Silas22@gmail.com",
      phone: "0944627892",
      fullname: "david Silas",
    },
    {
      id: "20",
      role: "front end",
      status: true,
      phone: "0944627892",
      email: "carmella@hotmail.com",
      fullname: "david carmella",
    },
  ],
  total: 20,
};
